//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulesExercise.Infrastructure.Persistence.Configurations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SeedTemplatesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeedTemplatesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RulesExercise.Infrastructure.Persistence.Configurations.SeedTemplatesResources", typeof(SeedTemplatesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;h4&gt;Hi there from {{ Name }} project&lt;/h4&gt;
        ///	&lt;ul&gt;
        ///		&lt;li&gt;Id : {{ Id }};&lt;/li&gt;
        ///        &lt;li&gt;Project Changed;&lt;/li&gt;
        ///	&lt;/ul&gt; 
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Smtp_message_1 {
            get {
                return ResourceManager.GetString("Smtp_message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	&lt;h4&gt;Project {{ Name }} was Deleted&lt;/h4&gt;
        ///	&lt;ul&gt;
        ///		&lt;li&gt;Id : {{ Id }};&lt;/li&gt;
        ///        &lt;li&gt;Project Deleted;&lt;/li&gt;
        ///	&lt;/ul&gt; 
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Smtp_message_2 {
            get {
                return ResourceManager.GetString("Smtp_message_2", resourceCulture);
            }
        }
    }
}
